#!/bin/bash

ln -s ../system/ionized.hmr.psf . 
ln -s ../system/ionized.pdb .

./get_initial_CA_pos

./gencolvars.py > hw.colvar.in

module load vmd/1.9.3

vmd -dispdev text -e get_cell.tcl 
vmd -dispdev text -e make_fixed.tcl 
vmd -dispdev text -e make_conskfile.tcl  -args "backbone" 10 1
vmd -dispdev text -e make_conskfile.tcl  -args "backbone" 8 2
vmd -dispdev text -e make_conskfile.tcl  -args "backbone" 6 3
vmd -dispdev text -e make_conskfile.tcl  -args "backbone" 4 4
vmd -dispdev text -e make_conskfile.tcl  -args "backbone" 2 5

cp -r ../md-1 ../md-2
cp -r ../md-1 ../md-3

